### ISSUE TITLE
Creation of module with name containing space does not work properly

### ISSUE THREAD

**Issue by pcamelio** [Inedo/inedox-inedocore#100]
Hello
When a name mdoule contains space, it can't be edit properly.

Steps to reproduce the error

Select a RAFT
Select Module
Create a new Module
Module Name : TEST-NAME >> Module can be editing properly
Module Name : TEST - NAME >> Module can't be editing properly
The module is display in Text mode and a message error is reported:
There were one or more errors processing your script:
[Error] Line 1: Expected {

OTTER 2.1
Best regards

**Comment by whatatripp** [comment]
Hello;

Module names may not contain a space. From the [formal grammar](https://inedo.com/support/documentation/executionengine/reference/formal-grammar), note that names are:

> No more than fifty characters: numbers (0-9), upper- and lower-case letters (a-Z), dashes (-), and underscores (_); must start with a letter, and may not start or end with a dash or underscore 

I've filed this as a bug to better validate in the UI: 
https://inedo.myjetbrains.com/youtrack/issue/OT-276

**Comment by pcamelio** [comment]
Hello
 
OK 
I should read more carefully the doc J
or you should make a French version ;-) (I should still need read the doc …)
 
Best Regards
 
Philippe
 
 
De : Alana Tripp [mailto:notifications@github.com] 
Envoyé : lundi 10 décembre 2018 08:59
À : Inedo/inedox-inedocore
Cc : PhilippeC.; Author
Objet : Re: [Inedo/inedox-inedocore] Creation of module with name containing space does not work properly (#100)
 
Hello;
Module names may not contain a space. From the formal grammar, note that names are:
No more than fifty characters: numbers (0-9), upper- and lower-case letters (a-Z), dashes (-), and underscores (_); must start with a letter, and may not start or end with a dash or underscore
I've filed this as a bug to better validate in the UI:
https://inedo.myjetbrains.com/youtrack/issue/OT-276
