### ISSUE TITLE
Pipeline Raft not working - Error 500 Value cannot be null. Parameter name: key - when editing a module

### ISSUE THREAD

**Issue by pcamelio** [Inedo/inedox-inedocore#101]
Hello,
I am looking to use pipeline raft. I think there is a bug , but I might be wrong.

Step to reproduce:

1. Create an environnement: **Env-TEST**
2. Create a GIT Raft : **Raft-Test** assign to **Env-TEST**
3. Create a module: **Module-Test**
4. Edit the module **Module-Test** and add whatever you want
5. Edit the **Raft-Test** properties: Check Restrict to pipeline rafts
6. Create Pipeline Raft : **Pipeline-Test**
7. Add **PL-TEST=Raft-Test** as Environment rafts
8. Select Assets
9. Select **Pipeline-Test** 
10. Edit **Module-Test** from Tab **PL-TEST** 

>Error 500 : Value cannot be null. Parameter name: key

OTTER 2.1
Regards
Philippe C.

**Comment by gdivis** [comment]
Hi Philippe,

We have logged this as [OT-270](https://inedo.myjetbrains.com/youtrack/issue/OT-270). It will be fixed in Otter 2.1.1, which should be available this week.
