### ISSUE TITLE
When start an orchestration Plan, the Plan Name is always the first of the proposed list

### ISSUE THREAD

**Issue by pcamelio** [Inedo/inedox-inedocore#113]
Hello
Test case 
- Make Job 1 in Plans/Orchestration
- Make Job 2 in Pla,s/Orchestration
Start Job 2.
The Create Job shows Job 1 as selected job whereas it should be Job 2 as it was in previous versions.
Regards
Philippe

**Comment by jrasch** [comment]
Hello,

Can you file this as a support ticket here: https://inedo.com/support/submit-ticket

This GitHub repository is for the InedoCore extension, and issues for the products themselves are not tracked here.

**Comment by pcamelio** [comment]
Oups sorry




Le 24 avr. 2019 18:11, jrasch <notifications@github.com> a écrit :
Hello,

Can you file this as a support ticket here: https://inedo.com/support/submit-ticket

This GitHub repository is for the InedoCore extension, and issues for the products themselves are not tracked here.
