### ISSUE TITLE
Create CreatePackage Operation

### ISSUE THREAD

**Issue by apapadimoulis** [Inedo/inedox-inedocore#114]

**Comment by gdivis** [comment]
@apapadimoulis Do you have any specific requirements beyond this?

    Create-Package
    (
        From: <SourceDirectory>,
        Include: **,
        Exclude: ...,
        Group: <group>,
        Name: <name>,
        Version: <version>,
        Metadata: %(...)
    );

**Comment by apapadimoulis** [comment]
Looks good! We can always add more if needed.

I'll use this for the docs instead of Exec upack.exe
________________________________
