### ISSUE TITLE
Add Option to Use Remote Server to Proxy HTTP Commands

### ISSUE THREAD

**Issue by apapadimoulis** [Inedo/inedox-inedocore#22]
Add UseServerInContext property to the HTTP Operations (category Options)

"When selected, this will proxy the HTTP calls through the server is in context instead of using the server Otter or BuildMaster is installed on. If the server in context is SSH-based, then an error will be raised."

**Comment by gdivis** [comment]
Should probably be called "ProxyRequest" for that description. Effectively, "use server in context" should be the default behavior.
