### ISSUE TITLE
Clarify docs and display name for Tag field

### ISSUE THREAD

**Issue by jrasch** [Inedo/inedox-inedocore#86]
In the general Get Source operation, the `Tag` field actually supports any `refname`.

A description should be added to that property to clarify, along with display name changes and an additional `ScripAliasAttribute("Ref")`

**Comment by BenLubar** [comment]
Did you mean to put this on inedox-git?

https://github.com/Inedo/inedox-git/blob/master/Git/Git.InedoExtension/Operations/GeneralGetSourceOperation.cs

**Comment by jrasch** [comment]
Whoops... yeah; I'll make another issue.
