### ISSUE TITLE
If/Else when testing is Variable is defined not working as expected

### ISSUE THREAD

**Issue by pcamelio** [Inedo/inedox-inedocore#87]
Hi
I made this plan.
The goal is to check if $ENV is set for the Plan.
By default $ENV doesn't exist.

```
# General
{
    # If/Else
    if $IsVariableDefined($ENV)
    {
        Log-Debug "ENV DEFINED";
    }
    else
    {
        Log-Debug "ENV NOT SET";
    }
}
```
**Step 1/**
Run the Plan without setting $ENV : 
- Expected result : DEBUG : ENV NOT SET
- Obtained result : Job in error 
```
Skipping collection run; execute only.
Collection run succeeded.
Beginning execution run...
=========== VM-089 - TEST ==============
Could not resolve variable $ENV.
Cleaning up temporary files on Inedo Agent (v??, VM-089:46336)...
Execution run complete.
Execution run failed.
````
How the function $IsVariableDefined should work ?

**Step 2/**
Run the plan and set $ENV=TEST
- Expected result : DEBUG : ENV DEFINED
- Obtained result : 
```
Skipping collection run; execute only.
Collection run succeeded.
Beginning execution run...
===========  ==============
**ENV NOT SET**
Execution run complete.
Execution run succeeded
```
The test result is in the wrong way. 
Regards

**Comment by apapadimoulis** [comment]
$IsVariableDefined(ENV)

Otherwise OtterScript runtime will try to replace before it even gets passed into function.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pcamelio** [comment]
Oups






Cordialement


Philippe Camelio







On Sun, Jul 1, 2018 at 8:12 AM +0200, "Alex Papadimoulis" <notifications@github.com> wrote:










$IsVariableDefined(ENV)



Otherwise OtterScript runtime will try to replace before it even gets passed into function.



Get Outlook for Android<https://aka.ms/ghei36>



________________________________
