### ISSUE TITLE
Add flag for recursive AD search

### ISSUE THREAD

**Issue by jrasch** [Inedo/inedox-inedocore#96]
Prior to a performance change in v1.0.6, this extension performed recursive AD group lookups by default. Some users prefer this behavior because the performance penalty does not warrant the maintenance hassle that occurs as a result.

Essentially, this issue should add a boolean flag to the AD user directory that determines whether recursive group search is enabled (noting in its description that it can cause performance issues).

The former method that handled this was here: https://github.com/Inedo/inedox-inedocore/commit/7f874470e8cf07d812a3dd3d948181b9f118826a#diff-eeb88218fa65bac519fe1d8570235edeL290

**Comment by ChristophLindemann** [comment]
Also I think it would be ok, if you could enable caching. This could speed up users that do frequent package management operations, like build servers.
You could only cache if permission was granted, so it would always make a full check if it was previously not granted.
In our case, it would not be a problem if the permissions would be cached for a few minutes.

**Comment by ChristophLindemann** [comment]
And you could give the following cases special treatment

- Anonymous users
- ApiKey with default "Feed API user" (no assigned user)

as you probably could do some shortcuts here without full AD lookup.

**Comment by jrasch** [comment]
Just a side note, but caching is currently done for the principal/task-attribute relationship at the user directory level, and if any privileges change, the full cache is expired. However, the performance issues were still prevalent on the initial load (i.e. it took ~10 secs to load the first page or respond to a NuGet request).

**Comment by ChristophLindemann** [comment]
I just thought about, that GetAuthorizationGroups() might probably be better to use, if the number of potential recursive group members is high. In such situations, enumeration of a users groups might be quicker than enumerating a groups full recursive member set.

**Comment by ChristophLindemann** [comment]
You could also start “continuously” enumerate, cache and synchronize the list of members for a given group in the background, as soon as the first lookup is done on a group.
Then only the first lookup is slow

**Comment by ChristophLindemann** [comment]
@BenLubar @jrasch @gdivis 
Can you please reopen this issue, as the fix in commit 6920faadb10a86295afc8e9563fe9d7db30218ec was reverted in c4dc032192091f6836714c63ec832f3cd8458a32 as part of #99.

So the issue (also described in [EDO-5293]) is actually not fixed.

**Comment by gdivis** [comment]
We have reimplemented this fix and released in the 1.0.11 InedoCore extension, which you should be able to install now.
